### ISSUE TITLE
大佬，来帮个忙呗，你看看这个需求怎么搞

### ISSUE THREAD

**Issue by hasbug** [vincentSea/gulp-demo#4]
因为在JS这个文件夹中我会用到类似layer/swiper之类的插件，独立一个文件夹，
例如：src>static>js>lib>layer 
但这些插件自带了css样式表，也希望能在输出output的时候，css也能被输出到原位置。

**Comment by scarecrowdu** [comment]
这个功能有提供的
直接根据你的目标结构、把文件放在根目录的static就行了
